server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
    #Config Server会默认从应用的src/main/resource目录下检索配置文件
  profiles: 
    active: native
    #属性文件地址，只要指定文件夹的路径
  cloud: 
     config: 
       server:
         native:
           searchLocations: classpath:/properties/
  rabbitmq: 
     host: 192.163.20.86
     port: 5672
     username: bh
     password: bh
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   ## 注册中心eurka地址
management:
  security:
     enabled: false

